# Generated by Django 5.2 on 2025-05-16 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('read_only_mode', models.CharField(choices=[('off', 'Off'), ('on', 'On')], default='off', max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_phase', models.CharField(blank=True, max_length=100)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('maintenance_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Database Statuses',
            },
        ),
        migrations.CreateModel(
            name='RefreshLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phase', models.CharField(max_length=100)),
                ('step', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_error', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Refresh Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StatusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('primary', 'Primary')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_display', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_display', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('dismissible', models.BooleanField(default=True)),
                ('display_on_all_pages', models.BooleanField(default=True)),
                ('specific_pages', models.CharField(blank=True, help_text='Comma-separated list of URL paths where this notification should appear', max_length=255)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
