# Generated by Django 5.2 on 2025-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='subtype_code',
            field=models.CharField(blank=True, db_index=True, help_text='Specific type within class, e.g., CEM I, Fly Ash Class F, ground_granulated_blast_furnace_slag', max_length=60, null=True),
        ),
    ]
