# Generated by Django 5.2 on 2025-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_app', '0002_alter_material_subtype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretemix',
            name='k_flag',
            field=models.BooleanField(default=False, help_text='Indicates if the w/b ratio considers k-value concept for SCMs'),
        ),
        migrations.AddField(
            model_name='concretemix',
            name='wb_k_reported',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Water/Binder ratio with k-value consideration (DIN 1045-2)', max_digits=6, null=True),
        ),
    ]
