# Generated by Django 5.2 on 2025-05-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_app', '0003_concretemix_k_flag_concretemix_wb_k_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.CharField(choices=[('EN', 'European Standards (EN)'), ('ASTM', 'US Standards (ASTM)')], max_length=10)),
                ('class_code', models.CharField(help_text='e.g., C25/30 for EN or 4000 for ASTM', max_length=20)),
                ('min_strength', models.DecimalField(decimal_places=2, help_text='Minimum required strength in MPa or psi', max_digits=8)),
                ('max_strength', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum strength for this class (if applicable)', max_digits=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Strength Class',
                'verbose_name_plural': 'Strength Classes',
                'db_table': 'strength_class',
                'ordering': ['standard', 'min_strength'],
                'unique_together': {('standard', 'class_code')},
            },
        ),
        migrations.CreateModel(
            name='MixStrengthClassification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification_method', models.CharField(choices=[('reported', 'Based on Reported Strength Class'), ('calculated', 'Calculated from 28-day Strength Results'), ('manual', 'Manually Classified')], max_length=20)),
                ('classification_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence level (0-100%) for automatically classified mixes', max_digits=5, null=True)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_classifications', to='cdb_app.concretemix')),
                ('strength_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb_app.strengthclass')),
            ],
            options={
                'verbose_name': 'Mix Strength Classification',
                'verbose_name_plural': 'Mix Strength Classifications',
                'db_table': 'mix_strength_classification',
                'unique_together': {('mix', 'strength_class')},
            },
        ),
    ]
