# Generated by Django 5.2 on 2025-05-21 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_app', '0004_strengthclass_mixstrengthclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretemix',
            name='air_content_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Air content percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='concretemix',
            name='density_kg_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fresh concrete density in kg/m³', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='concretemix',
            name='slump_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured slump in millimeters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='concretemix',
            name='target_strength_mpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target compressive strength in MPa', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='biblio_reference',
            field=models.ForeignKey(blank=True, help_text='Academic reference for the dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='cdb_app.bibliographicreference'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the dataset', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when data was first imported', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='last_import_date',
            field=models.DateTimeField(blank=True, help_text='Date when data was last updated', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='source',
            field=models.CharField(blank=True, help_text='Origin of the dataset', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='year_published',
            field=models.IntegerField(blank=True, help_text='Year when the dataset was published', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='density_kg_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material density in kg/m³', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='performanceresult',
            name='property',
            field=models.ForeignKey(blank=True, help_text='The specific property being measured', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='cdb_app.propertydictionary'),
        ),
    ]
