# Generated by Django 5.2.1 on 2025-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_app', '0005_concretemix_air_content_pct_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='material_class_c_c773fb_idx',
        ),
        migrations.RemoveField(
            model_name='concretemix',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='concretemix',
            name='references',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_class',
        ),
        migrations.RemoveField(
            model_name='material',
            name='standard',
        ),
        migrations.AddField(
            model_name='concretemix',
            name='dataset_id',
            field=models.IntegerField(blank=True, help_text='Dataset ID reference', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='brand_name',
            field=models.TextField(blank=True, help_text='Brand name from source', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='class_code',
            field=models.CharField(blank=True, help_text='Material class code e.g., CEMENT, SCM, AGGR_C, AGGR_F', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='standard_ref',
            field=models.CharField(blank=True, help_text='Standard reference', max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['class_code', 'subtype_code'], name='material_class_c_c773fb_idx'),
        ),
    ]
