# Generated by Django 5.2.1 on 2025-06-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_app', '0006_remove_material_material_class_c_c773fb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='material_class_c_c773fb_idx',
        ),
        migrations.RemoveField(
            model_name='concretemix',
            name='dataset_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='material',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='material',
            name='density_kg_m3',
        ),
        migrations.RemoveField(
            model_name='material',
            name='standard_ref',
        ),
        migrations.AddField(
            model_name='aggregatedetail',
            name='specific_gravity_od',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Oven-Dry Specific Gravity of aggregate particles', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedetail',
            name='specific_gravity_ssd',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Saturated Surface-Dry Specific Gravity of aggregate particles', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cementdetail',
            name='blaine_fineness_m2_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Blaine fineness in m²/kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cementdetail',
            name='bulk_density_kg_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bulk density of cement powder', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cementdetail',
            name='specific_gravity_od',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Oven-Dry Specific Gravity of cement particles', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='concretemix',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concrete_mixes', to='cdb_app.dataset'),
        ),
        migrations.AddField(
            model_name='concretemix',
            name='references',
            field=models.ManyToManyField(related_name='concrete_mixes', through='cdb_app.ConcreteMixReference', to='cdb_app.bibliographicreference'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_class',
            field=models.ForeignKey(blank=True, db_column='class_code', help_text='High-level material classification', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='materials', to='cdb_app.materialclass'),
        ),
        migrations.AddField(
            model_name='material',
            name='standard',
            field=models.ForeignKey(blank=True, db_column='standard_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='cdb_app.standard'),
        ),
        migrations.AddField(
            model_name='scmdetail',
            name='bulk_density_kg_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bulk density of SCM powder', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='scmdetail',
            name='specific_gravity_od',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Oven-Dry Specific Gravity of SCM particles', max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_class', 'subtype_code'], name='material_class_c_c773fb_idx'),
        ),
    ]
