# Generated by Django 5.2 on 2025-04-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete_mix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mixcomposition',
            options={'managed': True, 'verbose_name': 'Mix Composition', 'verbose_name_plural': 'Mix Compositions'},
        ),
    ]
