# Generated by Django 5.2 on 2025-05-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete_mix_app', '0003_reset_mixcomposition_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixcomposition',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mix_compositions', to='concrete_mix_app.material'),
        ),
        migrations.AddField(
            model_name='mixcomposition',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mix_compositions', to='concrete_mix_app.concretemix'),
        ),
    ]
